### PR TITLE
Strato new fix

### PR DESCRIPTION
**Pull request by steel101**
Fixed links 
Issus was closed with out linking being updated.

### CODE REVIEW

**Comment by steel101** [comment]
I told you this a bot and I will keep opening the same issue untill it fixed I check everyfew mins to see if it fixed

**Comment by TheASVigilante** [comment]
Well, you asked for it then

**Comment by steel101** [comment]
Thai is a automatic response the link is not updated

**Comment by steel101** [comment]
> Well, you asked for it then

Yes I have asked you to fix your app like links multi people have given to fix it and you won't so I set a bot to get it done by keeping pull request open

**Comment by steel101** [comment]
> > Well, you asked for it then
> 
> Yes I have asked you to fix your app like links multi people have given to fix it and you won't so I set a bot to get it done by keeping pull request open

My bot is ai powered sir so it won't stop until it has done what is programmed to do

**Pull request closed without merging**
