### PR TITLE
Link fix

### PR DESCRIPTION
**Pull request by steel101**
Fixed links

### CODE REVIEW

**Comment by TheASVigilante** [comment]
Look, i get it, we'll hard fork the sirit repo later

**Comment by steel101** [comment]
Give a true reason why you don't want to use a fork to fix your app. Lots of people have given you links to fix your shit so accept one or give a real reason no we will not use a fork when you here using a fork before so come on stop being petty and fix your app with people that have summited fixes

**Comment by steel101** [comment]
I have a bot set to keep opening the same issue untill it is fixed 2 weeks is way too long to update a link

**Comment by steel101** [comment]
> Look, i get it, we'll hard fork the sirit repo later

You. Don't get it 2 weeks with out update a link is crazy. How long does it take to update a link to fix it to make it work again

**Comment by TheASVigilante** [comment]
I'm busy with writing texman nowadays and since there is basically no reason to build the repo as is currently i've little reason to update the submodule

**Comment by TheASVigilante** [comment]
But sure if you want it so damn much

**Pull request closed without merging**
