### PR TITLE
Make navigation bar fully transparent

### PR DESCRIPTION
**Pull request by PabloG02**

### CODE REVIEW

**Review by lynxnb — APPROVED** [review]
LGTM, thanks!

**Review by Ishan09811 — CHANGES_REQUESTED** [review]
@lynxnb  @PabloG02 

Instead of using this method `android:enforceNavigationBarContrast` 
you can use this method 👇
`<item name="android:windowFullscreen">true</item>
    <item name="android:windowContentOverlay">@null</item>
    <item name="android:windowActionBarOverlay">true</item>
    <item name="android:windowTranslucentNavigation">true</item>
    <item name="android:windowBackground">@android:color/transparent</item>`

This code makes the app in full screen and also hide the nav bar instead of transperent method.

**Comment by lynxnb** [comment]
@Ishan09811 Have you tested that yourself? Can you post some before and after screenshots?

**Comment by Ishan09811** [comment]
> @Ishan09811 Have you tested that yourself? Can you post some before and after screenshots?

ok wait

**Comment by Ishan09811** [comment]
> @Ishan09811 Have you tested that yourself? Can you post some before and after screenshots
My code test is failed because it's break the white ui so i need to fix it and I will retry it ok ?

**Pull request merged**
