### PR TITLE
Update .gitmodules yuzu fork last day before they went down

### PR DESCRIPTION
**Pull request by steel101**
I forked yuzu the day before it went down I just made this repository available to the Public. This is the last link I'm submitting to you. I hope you accept this change. I would like it if you forked the repository to host it on your GitHub. Provided the last revision yuzu had before they took down there GitHub.

### CODE REVIEW

**Comment by Crytonics** [comment]
Duplicate of #254

**Comment by steel101** [comment]
This is a new link to a updated repository

**Comment by Crytonics** [comment]
> This is a new link to a updated repository

It is the same repo... You only change link.

**Comment by lynxnb** [comment]
Please stop with these. We won't accept any link to random user repositories.

**Comment by steel101** [comment]
So you won't accept a link to a fork you need. I asked you to fork it so you could host it

**Comment by steel101** [comment]
Wow you still have not got a replacement for it yet. 2 people have given you multi links to use and you say no makes no sense to me. Don't want your so to be built anymore

**Pull request closed without merging**
