### PR TITLE
More Optimised the FirmwareImportPreference.kt

### PR DESCRIPTION
**Pull request by Ishan0981**
Used CopyTo instead of copyRecursively for more speed and other small changes for better readability and optimisation

### CODE REVIEW

**Comment by Apethesis** [comment]
You just went from a recursive function to a loop, i don't think that'll make much of a difference in performance.
Also not sure but i think there was a reason for it being not in MainScope.

**Comment by Crytonics** [comment]
Never remove comments inside code if they left it inside. 
Also why did you remove spaces before :

**Comment by Crytonics** [comment]
@lynxnb

**Comment by Crytonics** [comment]
I am closing because there is some broken code and unnecessary changes with worse readability.

**Pull request closed without merging**
