### PR TITLE
add picture in picture option 

### PR DESCRIPTION
**Pull request by Ishan09811**

### CODE REVIEW

**Comment by QuackingCanary** [comment]
Hi Ishan, we reviewed your PR. That's a good idea but you should instead use an Intent to redirect the user directly to the app (system) settings using `startActivity(Intent("android.settings.PICTURE_IN_PICTURE_SETTINGS", Uri.parse("package:${packageName}")))` instead of creating a new setting in Strato

**Comment by Ishan09811** [comment]
@QuackingCanary 
your alternative idea is good but launching a intent to go system settings and manage the picture in picture is weird and time taking process also some people will not understand what is picture in picture and what it does so if we provide a option in the settings then the summary will inform the purpose of the option.

**Comment by QuackingCanary** [comment]
Screenshot_20240221-171146
You get a brief explanation of what Picture in Picture is when you reach the Intent. The setting is pointless since Android already has a solution

**Comment by Ishan09811** [comment]
@QuackingCanary 
While implementing a custom setting within the app can offer clarity and control,relying on system settings reduces the complexity of app and. However, it's essential to consider the user experience and preferences when making this decision, as some users may prefer managing settings directly within the app for convenience and accessibility so we need to talk with users for their suggestions.

**Pull request closed without merging**
